# render.yaml
services:
  - type: web
    name: ride-fare-estimator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    plan: free
